# ===============================
# Pure3XEngenie Configuration
# Version: 0.1.2 Alpha
# ===============================

engine_name=Pure3XEngenie
version=0.1.2 Alpha

fullscreen=false
debug=true

language=pt_BR
log_level=info
