# ==========================================
# Pure3XEngenie Configuration File
# Version: 0.1.4 Alpha
# ==========================================

[Engine]
Name=Pure3XEngenie
Version=0.1.4 Alpha
Language=English
Debug=true

[Boot]
ShowLogo=true
ShowProgressBar=true
BootDelay=120

[Logger]
Enabled=true
Level=INFO
SaveToFile=true
FileName=engine.log

[Network]
Enabled=true
AutoDetect=true

[Platform]
Target=Android

[Graphics]
Renderer=Auto
VSync=false

[Audio]
Enabled=true

[GameModules]
AutoLoad=true

[Assets]
Cache=true
